// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lorem-grpc/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoremRequest struct {
	RequestType          string   `protobuf:"bytes,1,opt,name=requestType,proto3" json:"requestType,omitempty"`
	Min                  int32    `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoremRequest) Reset()         { *m = LoremRequest{} }
func (m *LoremRequest) String() string { return proto.CompactTextString(m) }
func (*LoremRequest) ProtoMessage()    {}
func (*LoremRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e90116297b6670c3, []int{0}
}

func (m *LoremRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoremRequest.Unmarshal(m, b)
}
func (m *LoremRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoremRequest.Marshal(b, m, deterministic)
}
func (m *LoremRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoremRequest.Merge(m, src)
}
func (m *LoremRequest) XXX_Size() int {
	return xxx_messageInfo_LoremRequest.Size(m)
}
func (m *LoremRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoremRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoremRequest proto.InternalMessageInfo

func (m *LoremRequest) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *LoremRequest) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *LoremRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type LoremResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoremResponse) Reset()         { *m = LoremResponse{} }
func (m *LoremResponse) String() string { return proto.CompactTextString(m) }
func (*LoremResponse) ProtoMessage()    {}
func (*LoremResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e90116297b6670c3, []int{1}
}

func (m *LoremResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoremResponse.Unmarshal(m, b)
}
func (m *LoremResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoremResponse.Marshal(b, m, deterministic)
}
func (m *LoremResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoremResponse.Merge(m, src)
}
func (m *LoremResponse) XXX_Size() int {
	return xxx_messageInfo_LoremResponse.Size(m)
}
func (m *LoremResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoremResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoremResponse proto.InternalMessageInfo

func (m *LoremResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoremResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*LoremRequest)(nil), "pb.LoremRequest")
	proto.RegisterType((*LoremResponse)(nil), "pb.LoremResponse")
}

func init() {
	proto.RegisterFile("lorem-grpc/pb/service.proto", fileDescriptor_e90116297b6670c3)
}

var fileDescriptor_e90116297b6670c3 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0xc9, 0x2f, 0x4a,
	0xcd, 0xd5, 0x4d, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x48, 0xd2, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a, 0xe1, 0xe2, 0xf1,
	0x01, 0x29, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe0, 0xe2, 0x2e, 0x82, 0x30,
	0x43, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0x04, 0xb8,
	0x98, 0x73, 0x33, 0xf3, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x40, 0x4c, 0xb0, 0x48, 0x62,
	0x85, 0x04, 0x33, 0x54, 0x24, 0xb1, 0x42, 0xc9, 0x9a, 0x8b, 0x17, 0x6a, 0x6a, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0xcc, 0x48, 0x18,
	0x17, 0xa4, 0x39, 0xb5, 0xa8, 0x08, 0x6c, 0x1c, 0x67, 0x10, 0x88, 0x69, 0x64, 0xce, 0xc5, 0x0a,
	0xd6, 0x2c, 0xa4, 0x07, 0x63, 0x08, 0xe8, 0x15, 0x24, 0xe9, 0x21, 0x3b, 0x53, 0x4a, 0x10, 0x49,
	0x04, 0x62, 0x85, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x5b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x31, 0xc1, 0x33, 0xc5, 0xf5, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoremClient is the client API for Lorem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoremClient interface {
	Lorem(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error)
}

type loremClient struct {
	cc grpc.ClientConnInterface
}

func NewLoremClient(cc grpc.ClientConnInterface) LoremClient {
	return &loremClient{cc}
}

func (c *loremClient) Lorem(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error) {
	out := new(LoremResponse)
	err := c.cc.Invoke(ctx, "/pb.Lorem/Lorem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoremServer is the server API for Lorem service.
type LoremServer interface {
	Lorem(context.Context, *LoremRequest) (*LoremResponse, error)
}

// UnimplementedLoremServer can be embedded to have forward compatible implementations.
type UnimplementedLoremServer struct {
}

func (*UnimplementedLoremServer) Lorem(ctx context.Context, req *LoremRequest) (*LoremResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lorem not implemented")
}

func RegisterLoremServer(s *grpc.Server, srv LoremServer) {
	s.RegisterService(&_Lorem_serviceDesc, srv)
}

func _Lorem_Lorem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoremRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoremServer).Lorem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Lorem/Lorem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoremServer).Lorem(ctx, req.(*LoremRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lorem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Lorem",
	HandlerType: (*LoremServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lorem",
			Handler:    _Lorem_Lorem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorem-grpc/pb/service.proto",
}
